SUPABASE_URL = "https://vlvlinfktostbnqghjqf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsdmxpbmZrdG9zdGJucWdoanFmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQ4OTcyNywiZXhwIjoyMDg0MDY1NzI3fQ.fRNiYGTzv7L2H63wA4slm_wjieJkq0U_k4Lc-65wuGk"
